# Python Basic Programming Assignment 8

## 1. Write a Python Program to Add Two Matrices?

In [29]:
import numpy as np
def matricsAddition():
  
    R = int(input("Enter the number of rows:"))
    C = int(input("Enter the number of columns:"))
    
    print("\n If the no. of rows=3 and columns=3 then number of elements in matrix are (R*C) (3*3)=9")
    
    print("\nEnter the entries in a single line (separated by space): ")
    
    # User input of entries 
    # single line separated by space
    entries1 = list(map(int, input("Enter the no. of elements for 1st matrix: ").split()))
    entries2 = list(map(int, input("Enter the no. of elements for 2nd matrix: ").split()))

    # For printing the matrix
    matrix1 = np.array(entries1).reshape(R, C)
    matrix2 = np.array(entries2).reshape(R, C)
    print("\n matrix1=\n",matrix1)
    print("\n")
    print("matrix2=\n",matrix2)
    
    result = np.array(matrix1) + np.array(matrix2)
    print("\n Addition of 2 matrices")
    print(f"matrix1 +matrix2\n= {result}")

In [30]:
matricsAddition()

Enter the number of rows:2
Enter the number of columns:2

 If the no. of rows=3 and columns=3 then number of elements in matrix are (R*C) (3*3)=9

Enter the entries in a single line (separated by space): 
Enter the no. of elements for 1st matrix: 1 2 3 4
Enter the no. of elements for 2nd matrix: 1 2 3 4

 matrix1=
 [[1 2]
 [3 4]]


matrix2=
 [[1 2]
 [3 4]]

 Addition of 2 matrices
matrix1 +matrix2
= [[2 4]
 [6 8]]


## 2. Write a Python Program to Multiply two Matrices ?

In [31]:
def matricsMultiplication():
  
    R = int(input("Enter the number of rows:"))
    C = int(input("Enter the number of columns:"))
    
    print("\n If the no. of rows=3 and columns=3 then number of elements in matrix are (R*C) (3*3)=9")
    
    print("\nEnter the entries in a single line (separated by space): ")
    
    # User input of entries 
    # single line separated by space
    entries1 = list(map(int, input("Enter the no. of elements for 1st matrix: ").split()))
    entries2 = list(map(int, input("Enter the no. of elements for 2nd matrix: ").split()))

    # For printing the matrix
    matrix1 = np.array(entries1).reshape(R, C)
    matrix2 = np.array(entries2).reshape(R, C)
    print("\n matrix1=\n",matrix1)
    print("\n")
    print("matrix2=\n",matrix2)
    
    result = np.array(matrix1) * np.array(matrix2)
    print("\n Multiplication of 2 matrices")
    print(f"matrix1 * matrix2\n= {result}")

In [32]:
matricsMultiplication()

Enter the number of rows:3
Enter the number of columns:3

 If the no. of rows=3 and columns=3 then number of elements in matrix are (R*C) (3*3)=9

Enter the entries in a single line (separated by space): 
Enter the no. of elements for 1st matrix: 1 2 3 4 5 6 7 8 9
Enter the no. of elements for 2nd matrix: 1 2 3 4 5 6 7 8 9

 matrix1=
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


matrix2=
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 Multiplication of 2 matrices
matrix1 * matrix2
= [[ 1  4  9]
 [16 25 36]
 [49 64 81]]


## 3. Write a Python Program to Transpose a Matrix?

In [75]:
def matricsTranspose():
  
    R = int(input("Enter the number of rows:"))
    C = int(input("Enter the number of columns:"))
    
    print("\n If the no. of rows=3 and columns=3 then number of elements in matrix are (R*C) (3*3)=9")
    
    print("\nEnter the entries in a single line (separated by space): ")
    
    # User input of entries 
    # single line separated by space
    entries1 = list(map(int, input("Enter the no. of elements of matrix: ").split()))

    # For printing the matrix
    matrix1 = np.array(entries1).reshape(R, C)
    print("\n matrix1=\n",matrix1)
    print("\n")
    
    result = [[matrix1[j][i] for j in range(len(matrix1))] for i in range(len(matrix1[0]))]
    #for i in range(len(matrix1[0])) iterate through rows
    #for j in range(len(matrix1)) iterates through columns
    
    for r in result:
        print(r)

In [76]:
matricsTranspose()

Enter the number of rows:3
Enter the number of columns:3

 If the no. of rows=3 and columns=3 then number of elements in matrix are (R*C) (3*3)=9

Enter the entries in a single line (separated by space): 
Enter the no. of elements of matrix: 1 2 3 4 5 6 7 8 99

 matrix1=
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8 99]]


[1, 4, 7]
[2, 5, 8]
[3, 6, 99]


## 4. Write a Python Program to Sort Words in Alphabetic Order?

In [98]:
def wordSorting():
    string = input("Type the words in random alphabetical order:")
    lists=string.split()
    print(lists)
    lists.sort()
    
    sortedlist=[]
    for word in lists:
        sortedlist.append(word)
    print(f"\n The sorted list in alphabetical order {sortedlist}")  

In [100]:
wordSorting()

Type the words in random alphabetical order:dog bear cat tiger lion 
['dog', 'bear', 'cat', 'tiger', 'lion']

 The sorted list in alphabetical order ['bear', 'cat', 'dog', 'lion', 'tiger']


## 5. Write a Python Program to Remove Punctuation From a String?

In [101]:
import string
 
def removePunctuations():
    sentence=input("Write a sentence with punctuations")
    sentence = sentence.translate(str.maketrans('', '', string.punctuation))
    print(f"\nSentence without punctuations:{sentence}")

In [102]:
removePunctuations()

Write a sentence with punctuationsI don't often go swimming; I prefer to play tennis.

Sentence without punctuations:I dont often go swimming I prefer to play tennis


In [103]:
removePunctuations()

Write a sentence with punctuationsShubh@gmail_19.com///?

Sentence without punctuations:Shubhgmail19com
